using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using MarcelJoachimKloubert.DWAD;
using MarcelJoachimKloubert.DWAD.WADs.Lumps.Linedefs;
using MarcelJoachimKloubert.DWAD.WADs.Lumps.Sectors;
using MarcelJoachimKloubert.DWAD.WADs.Lumps.Things;
using MarcelJoachimKloubert.DWAD.WADs.Lumps.Vertexes;

namespace WAD2WMP
{
    internal class Program
    {
        private const string WMPHeaderTemplate = "#  This file \"{0}\" was generated by WED v3.29\r\n#  World EDitor for 3D GameStudio by conitec GmbH 1996/1997\r\n#  creation date: {1}    time: {2}";
        private const string WMPVertexHeaderTemplate = "\r\n\r\n\r\n\r\n#vertex\txpos ypos zpos index\r\n#-------------------------------\r\n";
        private const string WMPRegionHeaderTemplate = "\r\n\r\n\r\n\r\n#region\tname\tfloor_hgt\tceil_hgt\r\n#---------------------------------\r\n";
        private const string WMPWallsHeaderTemplate =  "\r\n\r\n\r\n\r\n#wall\tname vertex vertex\tregion region\toffsx offsy\tindex\r\n#------------------------------------------------------------\r\n";
        private const string WMPThingsHeaderTemplate = "\r\n\r\n\r\n\r\n#player_start\r\n#thing\r\n#actor name xpos ypos angle region index\r\n#---------------------------------------\r\n";
        private const string WMPVertexTemplate = "VERTEX\t{0} {1} 0;#{2}\r\n";
        private const string WMPWallTemplate = "WALL\t{0} {1} {2} {3} {4};#{5}\r\n";
        private const string WMPRegionTemplate = "REGION\t{0} {1} {2};#{3}\r\n";
        private const string WMPThingTemplate = "{0}\t{1} {2} {3} {4};#{5}\r\n";

        private const string WDLHeaderTemplate = "MAP {0};\r\n";
        private const string WDLRegionTemplate = "REGION {0} {{\r\n\tCEIL_TEX {1};\r\n\tFLOOR_TEX {2};\r\n}}\r\n";

        private const string DummyTextureName = "DUMMY";
        private const string BorderRegionName = "BORDER";

        private static bool IsValidPath(string path)
        {
            var directory = Path.GetDirectoryName(path);
            var filename = Path.GetFileName(path);
            var invalidChars = Path.GetInvalidFileNameChars();
            return directory != null && filename.IndexOfAny(invalidChars) < 0;
        }

        static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            if (args.Length < 3)
            {
                Console.WriteLine("WAD2WMP - Usage: <Input WAD Path> <Output WMP Path> <Output WDL Path>");
                Console.ReadKey();
                return;
            }
            var wadPath = args[0];
            if (!IsValidPath(wadPath) || !File.Exists(wadPath))
            {
                Console.WriteLine($"\"{wadPath}\" not found");
                Console.ReadKey();
                return;
            }
            var wmpPath = args[1];
            if (!IsValidPath(wmpPath))
            {
                Console.WriteLine($"\"{wmpPath}\" is not a valid path");
                Console.ReadKey();
                return;
            }
            var wdlPath = args[2];
            if (!IsValidPath(wdlPath))
            {
                Console.WriteLine($"\"{wdlPath}\" is not a valid path");
                Console.ReadKey();
                return;
            }
            var wmpFilename = Path.GetFileNameWithoutExtension(wmpPath);
            using (var wdlStream = File.Create(wdlPath))
            {
                using (var wdlStreamWriter = new StreamWriter(wdlStream))
                {
                    wdlStreamWriter.Write(WDLHeaderTemplate, wmpFilename);
                    wdlStreamWriter.Write(WDLRegionTemplate, BorderRegionName, DummyTextureName, DummyTextureName);
                    using (var wmpStream = File.Create(wmpPath))
                    {
                        using (var wmpStreamWriter = new StreamWriter(wmpStream))
                        {
                            using (var wadStream = File.OpenRead(wadPath))
                            {
                                foreach (var wadFile in WADFileFactory.FromStream(wadStream))
                                {
                                    var allSectors = wadFile
                                        .EnumerateLumps()
                                        .OfType<ISectorsLump>()
                                        .SelectMany(x => x.EnumerateSectors()).ToArray();
                                    var allVertices = wadFile
                                        .EnumerateLumps()
                                        .OfType<IVertexesLump>()
                                        .SelectMany(x => x.EnumerateVertexes()).ToArray();
                                    var allThings = wadFile
                                        .EnumerateLumps()
                                        .OfType<IThingsLump>()
                                        .SelectMany(x => x.EnumerateThings()).ToArray();
                                    var allLinedefs = wadFile
                                        .EnumerateLumps()
                                        .OfType<ILinedefsLump>()
                                        .SelectMany(x => x.EnumerateLinedefs()).ToArray();

                                    wmpStreamWriter.Write(WMPHeaderTemplate);

                                    var vertexIndex = 0;
                                    wmpStreamWriter.Write(WMPVertexHeaderTemplate);
                                    foreach (var vertex in allVertices)
                                    {
                                        wmpStreamWriter.Write(WMPVertexTemplate, vertex.X, vertex.Y, vertexIndex++);
                                    }

                                    var sectorIndex = 0;
                                    wmpStreamWriter.Write(WMPRegionHeaderTemplate);
                                    wmpStreamWriter.Write(WMPRegionTemplate, BorderRegionName, 0f, 0f, sectorIndex++);
                                    foreach (var sector in allSectors)
                                    {
                                        var regionName = $"REGION{sectorIndex}";
                                        wmpStreamWriter.Write(WMPRegionTemplate, regionName, sector.FloorHeight, sector.CeilingHeight, sectorIndex++);
                                        wdlStreamWriter.Write(WDLRegionTemplate, regionName, sector.FloorTexture, sector.CeilingTexture);
                                    }

                                    var wallIndex = 0;
                                    wmpStreamWriter.Write(WMPWallsHeaderTemplate);
                                    foreach (var linedef in allLinedefs)
                                    {
                                        var wallName = $"WALL{wallIndex}";
                                        var rightSide = linedef.RightSide;
                                        var leftSide = linedef.LeftSide;
                                        var vIndex1 = Array.IndexOf(allVertices, linedef.Start);
                                        var vIndex2 = Array.IndexOf(allVertices, linedef.End);
                                        var rightSideIndex = rightSide == null ? 0 : Array.IndexOf(allSectors, rightSide.Sector) + 1;
                                        var leftSideIndex = leftSide == null ? 0 : Array.IndexOf(allSectors, leftSide.Sector) + 1;
                                        wmpStreamWriter.Write(WMPWallTemplate, wallName, vIndex1, vIndex2, rightSideIndex, leftSideIndex, rightSide.XOffset, rightSide.YOffset, wallIndex++);
                                    }

                                    var thingIndex = 0;
                                    wmpStreamWriter.Write(WMPThingsHeaderTemplate);
                                    foreach (var thing in allThings)
                                    {
                                        if (thing.Type == 1)
                                        {
                                            wmpStreamWriter.Write(WMPThingTemplate, "PLAYER_START", thing.X, thing.Y, thing.Angle, FindRegion(thing), thingIndex++);
                                        }
                                    }

                                    return;
                                }
                            }
                        }
                    }
                }
            }
        }

        private static string FindRegion(IThing thing)
        {
            return "0";
        }
    }
}
